model_saved_name: ./runs/ntu120_xsub_bone_motion
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu120/xsub/train_data_bone_motion.npy
  label_path: ./data/ntu120/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/ntu120/xsub/val_data_bone_motion.npy
  label_path: ./data/ntu120/xsub/val_label.pkl

# model
model: model.model.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'disentangle'
    num_scales: 6
  out_channels: 500

#optim
weight_decay: 0.0005
base_lr: 0.05
step: [25, 35]
warm_up_epoch: 5

# training
device: 0
batch_size: 32
subdivision: 2
test_batch_size: 16
num_epoch: 50
nesterov: True

only_train_part: True
only_train_epoch: 5